### ISSUE TITLE
Provide a self explained gravitee.yml

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/gravitee-management-rest-api#28]
It will be more efficient to discover how to configure things in gravitee.yml instead of reading the documentation.

Like how Maven handle this in settings.xml

**Comment by M3lkior** [comment]
You can make a process that will automatically generate gravitee.yml with comments and default values, based on metadata files likes Spring-boot metadatas format : 

```
 "properties": [
    {
      "name": "banner.charset",
      "type": "java.nio.charset.Charset",
      "description": "Banner file encoding.",
      "defaultValue": "UTF-8"
    },
     {
      "name": "logging.exception-conversion-word",
      "type": "java.lang.String",
      "description": "Conversion word used when logging exceptions.",
      "sourceType": "org.springframework.boot.logging.LoggingApplicationListener",
      "defaultValue": "%wEx"
    }]
```

You can also plan to develop a CONFIGURER (also based on metadata files ? ;) ), which allows users to easily generate his gravitee.yml by answering configurer's questions.
This will be a nice feature !
