### ISSUE TITLE
Repository implementation for ${analytics.type} can not be found. Please add correct module in classpath

### ISSUE THREAD

**Issue by M3lkior** [gravitee-io/gravitee-management-rest-api#30]
Gravitee-management-api throws this error when trying to start it : 

```
Repository implementation for ${analytics.type} can not be found. Please add correct module in classpath
```

I have no configuration for analytics. It is possible to not automatically try to load an analytics repository if no configurations referes to it ? or add a way to disable this functionnality.

Thanks

**Comment by brasseld** [comment]
Analytics repository is required by the solution. We can't disable it by any way.
