### ISSUE TITLE
Throws unexpected error at : instance/monitoring

### ISSUE THREAD

**Issue by Tony-Proum** [gravitee-io/gravitee-management-rest-api#77]
Hi,

I got an Unexpected Error when trying to see instance monitoring screen. According to management api logs, It'seems this error is due to a downtime of my elasticsearch cluster.

I guess that the error should be more explicite.

see attached files to see error log

[RestApi.txt](https://github.com/gravitee-io/gravitee-management-rest-api/files/262950/RestApi.txt)

**Comment by brasseld** [comment]
Hi @Tony-Proum,

According to your log, you're using our Docker containers.
Is the elasticsearch container really down ?

**Comment by Tony-Proum** [comment]
Yes I used gravitee containers linked with own elasticsearch container, In my first post, I thought the link between gravitee management api and ES was broken. According to api logs, It's seems to request ES on the wrong container address : I can't figure out why org.elasticsearch.client.transport try to reach elasticsearch on **mongo**/10.7.0.26:**9300**

ES container is running, but gravitee api request is a mix between environment variables : 
    - ES_HOST=elasticsearch
    - ES_PORT=**9300**
    - MONGO_HOST=**mongo**
    - MONGO_PORT=27017
I got the right port, but the wrong host. Do you think I need to open an second issue in gravitee-docker project ?

**Comment by brasseld** [comment]
This issue was moved to gravitee-io/gravitee-docker#3
